apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-servicequalification
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{.Release.Name}}-servicequalification
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Values.component.name}}
        impl: {{.Release.Name}}-servicequalification
        version: {{.Values.api.versionLabel}}
    spec:
      containers:
        - name: {{.Release.Name}}-servicequalification
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: RELEASE_NAME
              value: "{{.Release.Name}}-servicequalification"
