apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-servicequalification
  labels:
    app: {{.Release.Name}}-{{.Values.component.name}}
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  type: {{ .Values.service.type }}
  selector:
    impl: {{.Release.Name}}-servicequalification
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      name: http-{{.Release.Name}}-servicequalification
